### ISSUE TITLE
Cannot execute ebup example

### ISSUE THREAD

**Issue by UdoW** [asciidoctor/asciidoctor-maven-examples#102]
I get this error when executing the ebug example:
`[ERROR] Failed to execute goal org.asciidoctor:asciidoctor-maven-plugin:2.0.0:process-asciidoc (generate-spine-kf8) on project asciidoctor-epub-example: Execution generate-spine-kf8 of goal org.asciidoctor:asciidoctor-maven-plugin:2.0.0:process-asciidoc failed: org.jruby.exceptions.IOError: (IOError) Cannot run program "kindlegen.exe" (in directory "M:\projects\asciidoctor_maven_extension\asciidoctor-maven-examples\asciidoctor-epub-example\src\docs\asciidoc"): CreateProcess error=2, Das System kann die angegebene Datei nicht finden -> [Help 1]`

I searched for the kindlegen.exe file and found this Amazon page:
https://www.amazon.com/gp/feature.html?ie=UTF8&docId=1000765211

So the kindle previewer should be used instead?

**Comment by abelsromero** [comment]
You can track the evolution in https://github.com/asciidoctor/asciidoctor-epub3/issues/363.
