### ISSUE TITLE
revealjs example does not work with reveal.js 4.1.0

### ISSUE THREAD

**Issue by wimdeblauwe** [asciidoctor/asciidoctor-maven-examples#112]
If you change the reveal.js version in the `pom.xml` to the latest 4.1.0:

```
<revealjs.version>4.1.0</revealjs.version>
```

then the HTML is generated, but the presentation does not seem to work.

**Comment by abelsromero** [comment]
Work to make `asciidoctor-revealjs` compatible with v4.x.x began recently: https://github.com/asciidoctor/asciidoctor-reveal.js/pull/431

**Comment by abelsromero** [comment]
A RC has been released with support for reveal.js 4.1.2 https://rubygems.org/gems/asciidoctor-revealjs/versions/5.0.0.rc1.

To use it yourself:

1. Upgrade version to `5.0.0.rc1` in https://github.com/asciidoctor/asciidoctor-maven-examples/blob/b8b835b9d74b38533aed148a37ce805b20ec12bb/asciidoc-to-revealjs-example/pom.xml#L28
2. Delete custom `monokai.css`, no longer needed.
3. Use this attributes (inly diference is replacing `customcss` by `rouge-style`, and removing `<rouge-css>class</rouge-css>` which is already the default value)
```xml
                            <attributes>
                                <!--
                                    As we are downloading reveal.js in runtime, it sits in a nonstandard folder `reveal.js-${revealjs.version}`
                                -->
                                <revealjsdir>reveal.js-${revealjs.version}</revealjsdir>
                                <!-- put here the reveal.js specific attributes -->
                                <sourcedir>${basedir}/src/main/java</sourcedir>
                                <revealjs_theme>black</revealjs_theme>
                                <revealjs_transition>linear</revealjs_transition>
                                <project-version>${project.version}</project-version>
                                <!-- can use any pygments/rouge css here -->
                                <rouge-style>monokai</rouge-style>
                                <source-highlighter>rouge</source-highlighter>
                            </attributes>
```

**Comment by abelsromero** [comment]
Fixed with PR https://github.com/asciidoctor/asciidoctor-maven-examples/pull/144
