### ISSUE TITLE
 asciidoctor: WARN: could not embed image: PNG uses unsupported interlace method

### ISSUE THREAD

**Issue by bonigarcia** [asciidoctor/asciidoctor-maven-examples#121]
Hello,

I'm experiencing a problem with the `asciidoctorj-pdf` Maven plugin that can be easily reproduced using the example project [asciidoctor-pdf-example](https://github.com/asciidoctor/asciidoctor-maven-examples/tree/main/asciidoctor-pdf-example). This project uses an JPG image. Simply changing the following line (in this [file](https://github.com/asciidoctor/asciidoctor-maven-examples/blob/main/asciidoctor-pdf-example/src/docs/asciidoc/example-manual.adoc)) to use a PNG (that should be placed in this [folder](https://github.com/asciidoctor/asciidoctor-maven-examples/tree/main/asciidoctor-pdf-example/src/docs/asciidoc/images)) instead of JPG:

```
image::sunset.jpg[scaledwidth=75%]
```

For example like this (sing this [picture](https://cdn2.iconfinder.com/data/icons/ios-7-icons/50/download2-256.png)):

```
image::download2-256.png[scaledwidth=75%]
```

After that, we try to build the PDF using Maven as usual:

```
mvn
```

We can see a warning in the Maven log, and then the picture is not displayed in the PDF.

```
[INFO] Scanning for projects...
[INFO]
[INFO] -----------< org.asciidoctor.maven:asciidoctor-pdf-example >------------
[INFO] Building Asciidoctor PDF Maven example 1.0.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- asciidoctor-maven-plugin:2.2.1:process-asciidoc (generate-pdf-doc) @ asciidoctor-pdf-example ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Using 'UTF-8' encoding to copy filtered properties files.
[INFO] Copying 4 resources
[INFO] asciidoctor: WARN: could not embed image: C:/Users/boni/dev/asciidoctor-maven-examples/asciidoctor-pdf-example/src/docs/asciidoc/images/download2-256.png; PNG uses unsupported interlace method; install prawn-gmagick gem to add support
[INFO] Converted C:\Users\boni\dev\asciidoctor-maven-examples\asciidoctor-pdf-example\src\docs\asciidoc\example-manual.adoc
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ asciidoctor-pdf-example ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Users\boni\dev\asciidoctor-maven-examples\asciidoctor-pdf-example\src\main\resources
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
```

It seems related to [this](https://github.com/asciidoctor/asciidoctor-pdf/issues/1578), but I don't know if this problem can be solved when using the Maven plugin.

**Comment by abelsromero** [comment]
No good news :disappointed: 

Same as the linked issue that image requires an extra gem for it's manipulation. It's working fine from Ruby, but not from Java.

You can include Ruby gems same way we do in the revealjs example, but this one `prawn-gmagick` requires compiling a native component which fails when run through jruby. Installing in Ruby with `gem install` works fine provided you have the build deps (`graphicsmagick` in my distro).
Furthermore, if you can get it compile in jruby, you are subject to https://github.com/asciidoctor/asciidoctor-maven-examples/issues/98, which means you are stuck with jRuby v9.2.9.0.
Even furthermore...if you want it to compile in Windows it will get even more complicated :sob: 

My recomendation would be trying to build it with Ruby, with `asciidoctor-pdf` and `prawn-gmagick` gem installed I could convert the PDF containing the image. If switching runtime is an issue, you can explore using docker image https://github.com/asciidoctor/docker-asciidoctor and installing the gem on top of it.

**Comment by mojavelinux** [comment]
You're correct that the prawn-gmagick suggestion only applies when you are using C Ruby.

In theory, it's possible to have something like prawn-gmagick that uses Java's image processing library to read the image instead of gmagick (or even something like https://github.com/jcupitt/ruby-vips). I just don't have the time or motivation to explore that thread myself.

I'd say the truly simple solution, as Abel suggested, is to flatten PNG images so that they don't use the interlace method at all. It's unsupported for a reason. It complicates image processing tremendously. This doesn't mean you can't use PNG. It's not a format issue. It's the fact that the image is not optimized properly.

**Comment by abelsromero** [comment]
I am going to close this then. @bonigarcia if you have any other question or need support exploring other build options, feel free to drop them at https://asciidoctor.zulipchat.com/, that's much better for questions like this one.
