### ISSUE TITLE
asciidoc-maven-site-example does not include 'hello.adoc' in site

### ISSUE THREAD

**Issue by danbress** [asciidoctor/asciidoctor-maven-examples#13]
I cloned the repo, went into 'asciidoc-mavne-site-example' ran mvn site:site, which worked, but the file generated from 'hello.adoc' is not included in the site output

using mvn 3.2.5
mvn-site-plugin:3.3

What am I doing wrong?

**Comment by mojavelinux** [comment]
The file must be named with an `.ad` extension at the moment. We misunderstood how multiple file extensions can be supported, so when we added `.adoc` it didn't actually work.

I'll push an update that uses the file name `hello.ad` for now to avoid confusion.

**Comment by mojavelinux** [comment]
For more context, see https://github.com/asciidoctor/asciidoctor-maven-plugin/issues/125
