### ISSUE TITLE
Cannot get my asciidoc to consistently read in Maven properties

### ISSUE THREAD

**Issue by rickbansal-mulesoft** [asciidoctor/asciidoctor-maven-examples#130]
Hi, not sure what I'm doing wrong but I cannot get my asciidoc to consistently read in Maven properties define in my pom.xml file.

Here's a snipped of  the pom file:

`	<properties>
		<opentelemetry.version>1.9.1</opentelemetry.version>
		<maven.build.timestamp.format>MM-dd-yyyy</maven.build.timestamp.format>
	</properties>

	<parent>
		<groupId>org.mule.extensions</groupId>
		<artifactId>mule-modules-parent</artifactId>
		<version>1.1.3</version>
	</parent>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-source-plugin</artifactId>
				<executions>
					<execution>
						<id>attach-sources</id>
						<goals>
							<goal>jar</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.asciidoctor</groupId>
				<artifactId>asciidoctor-maven-plugin</artifactId>
				<version>2.2.2</version>
				<executions>
					<execution>
						<id>asciidoc-to-html</id>
						<phase>generate-resources</phase>
						<goals>
							<goal>process-asciidoc</goal>
						</goals>
						<configuration>
							
							<attributes>
								<revnumber>${project.version}</revnumber>
								<revdate>${maven.build.timestamp}</revdate>
								<source-highlighter>coderay</source-highlighter>
							</attributes>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>`

And here is a bit of the asciidoc:
`= Mule 4 OpenTelemetry (OTel) Agent Extension
// Document header
Rick Bansal <rick.bansal@mulesoft.com>
:revnumber: {revnumber}
:revdate: {revdate}
:revremark: Initial Draft
:doctype: book
:icons: font
:toc: left
:keywords: Mule, MuleSoft, Observability, OpenTelemetry, OTel, Tracing, Instrumentation, Distributed`

Image of the html output:
<img width="1128" alt="Screen Shot 2022-02-28 at 10 34 06 AM" src="https://user-images.githubusercontent.com/43295907/156021365-6021fe3e-9f3e-4349-8eaa-df14a2b7aa28.png">

Please advise.  Thanks

**Comment by abelsromero** [comment]
I could no see any issues with your configuration, but also this is not complete. Could be some parent project or other configuration is overriding the attributes somehow?

I applied the attributes to your file succesfully. I only removed the `rev` attributes from the header section (no need to re-define those), and displayed the attributes also in the section at the bottom.

```
= Mule 4 OpenTelemetry (OTel) Agent Extension
// Document header
Rick Bansal <rick.bansal@mulesoft.com>
:revremark: Initial Draft
:doctype: book
:icons: font
:toc: left
:keywords: Mule, MuleSoft, Observability, OpenTelemetry, OTel, Tracing, Instrumentation, Distributed

== Values

revnumber: {revnumber}
revdate: {revdate}
```


![image](https://user-images.githubusercontent.com/5781153/156065117-9d200db6-9b98-439e-b611-3d5001102ed9.png)


PS: you can use markdown code blocks for examples (3 ticks ```), that will keep the format https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#fenced-code-blocks.

**Comment by rickbansal-mulesoft** [comment]
Abel, thanks for your response.  I've attached the entire (effective) pom.xml file for your reference.  Btw, I'm using the AsciiDoctor Eclipse plug-in and not sure if that maters. 
<img width="756" alt="Screen Shot 2022-02-28 at 4 44 03 PM" src="https://user-images.githubusercontent.com/43295907/156070989-cd0550c9-11df-44ea-a086-d957c82e6355.png">
[pom-xml.txt](https://github.com/asciidoctor/asciidoctor-maven-examples/files/8157408/pom-xml.txt)

**Comment by abelsromero** [comment]
> AsciiDoctor Eclipse plug-in and not sure if that maters.

For my testing I am running the maven build from terminal. Afaik the eclipse plugin is a separate component only for the preview which does not read maven configurations. Is your capture from maven build or the eclipse preview?

I could not run your pom, it still holds some references to other poms but the maven section seems complete.

**Comment by rickbansal-mulesoft** [comment]
From the maven build, executed through eclipse (I.e., not from the command line)

**Comment by abelsromero** [comment]
I know it's tedious, but can you run from terminal to confirm eclipse is not messing? what the plugin does is quite simple, just inject project properties as-is https://github.com/asciidoctor/asciidoctor-maven-plugin/blob/0aa5121249890c5db7c78b7c82e2ad387f38719e/src/main/java/org/asciidoctor/maven/process/AsciidoctorHelper.java#L35 (with some formatting that does not apply to your case).
And I don't see anything in the pom, but without being able to run it locally I cannot debug further.

**Comment by rickbansal-mulesoft** [comment]
I've cleaned up my pom.xml to remove some of the warnings that I was getting and seems like things are working as expected wrt to asciidoctor.  thanks.

**Comment by abelsromero** [comment]
If you have any other questions or experience that does not quite match a bug, feel free to drop by https://asciidoctor.zulipchat.com/
