### ISSUE TITLE
Add an example showing how to load a custom extension from a local file

### ISSUE THREAD

**Issue by abelsromero** [asciidoctor/asciidoctor-maven-examples#16]
As discuessed in http://discuss.asciidoctor.org/Maven-plugin-and-extensions-td3149.html#a3151, an example showing extension loading from local ruby files.
Current examples rely on gem-maven-plugin and torquebox repo to load ruby extensions, which is not always possible.

**Comment by jmini** [comment]
I have worked on an other aspect: creating an asciidoctorj extension (written in java) built with maven and consumed by an other documentation maven project.

The example can be seen in this commit: 7a4deee434ee145b831da0a8174fa6e135221a8a

Related discussion: [example of an asciidoctorj extension using java and maven](
http://discuss.asciidoctor.org/example-of-an-asciidoctorj-extension-using-java-and-maven-td3370.html)

**Comment by mojavelinux** [comment]
I like the idea of having an example of a Java-based extension and an example of a Ruby-based extension. That way, we can demonstrate both options.

**Comment by jmini** [comment]
Ok I have opened a pull request: #20 for the java example. Maybe the project should be renamed `java-extension-example` (instead of `extension-example`). 

This way a `ruby-extension-example` could be created to solve this issue.
