### ISSUE TITLE
Add checkstyle checking

### ISSUE THREAD

**Issue by abelsromero** [asciidoctor/asciidoctor-maven-examples#22]
(Related to https://github.com/asciidoctor/asciidoctor-maven-examples/pull/21) Include some [checkstyle maven plugin](https://maven.apache.org/plugins/maven-checkstyle-plugin/) rules.

As a proposal, I think we *should* add these formating rules at least:
* PackageName
* FileTabCharacter

Then also, being examples, we could add some rules to encourage documenting the classes:
* JavadocMethod
* JavadocType

Any other suggestions?

**Comment by abelsromero** [comment]
I haven't been able to find a clean solutions for this issue.

The main problems found are:
* The Checkstyle maven plugin does not provide a solution for a layout like this one where child projects do not define the parent. The solution provided involves creating a project to contain the configuration, see http://maven.apache.org/plugins/maven-checkstyle-plugin/examples/multi-module-config.html.
* Alternatives like inline pom configuration using `<checkstyleRules>` don't seem to work.

Overall the plugin has many issues and the only working solution found is defining the property `checkstyle.config.location` with the absolute path to the rule's XML file.
It is possible to set something like `../rules.xml` (provided the file is in the parent folder), but this only allows to check projects in the first depth level. Asciidoctor Extension's projects wont' be checked, and thore are imho the most important to check since they contain real code.

Other alternatives I can think of are:
* Add the XML rules and describe how to check the rules with external tools in the documentation: this makes the process cumbersone and not very usefull. Honestly, not even me will run the checks if I have to use a console tool or configure eclipse/intellJ.
* Invoke checkstyle from a custom script: same as before makes the process cumbersome and adds the complexity of handling the required checkstyle jars.
* Manual script to check some simple rules like tabs: it could even apply fixes directly, the problem I see is that I don't like the idea of writting scripts for eveything.

Btw, I've been looking into other tools and (surprisingly) haven't found anything usefull, I'm open to suggestions.

So, very regretfully I'll just close this issue with a 'wontfix' tag in a couple of days, and assume we'll need to keep bothering people with our code reviews.

**Comment by mojavelinux** [comment]
Thanks for this detailed analysis, Abel! The results are unfortunate, but knowing is half the battle.

>  we'll need to keep bothering people with our code reviews.

Code reviews in general are really good step to take anyway because we get to interact. One way we could preempt mistakes up front is to simply have (and update) a styleguide in the README anytime we see something that needs to be remembered.

**Comment by mojavelinux** [comment]
> Invoke checkstyle from a custom script: same as before makes the process cumbersome and adds the complexity of handling the required checkstyle jars.

I think in time something like this will evolve naturally and we'll get used to using it. I tend to use a lot of scripts to handle small tasks and, while they aren't perfectly integrated, they still save time.

**Comment by abelsromero** [comment]
OK then :+1: I'll add the style guides at least and try to make a small script to fix tabs, it's not much time.

> I think in time something like this will evolve naturally and we'll get used to using it. I tend to use a lot of scripts to handle small tasks and, while they aren't perfectly integrated, they still save time

That's what I like about gradle. In Maven I always end up with lots of profiles calling plugins and scritps which are in fact tasks.
