### ISSUE TITLE
Can't pass custom attribute into source block

### ISSUE THREAD

**Issue by vicmosin** [asciidoctor/asciidoctor-maven-examples#33]
[This example] (https://github.com/asciidoctor/asciidoctor-maven-examples/tree/master/asciidoc-to-html-example) shows how to pass custom attributes to asiidoc. Everything works fine until I put `{project-version}` inside `[source,xml]` block. Is it standard behavior or bug?

**Comment by abelsromero** [comment]
I've tested this and attributes are not replaced in source blocks, no matter if they come from the pom or they are defined in the AsciiDoc document. However, they are replaced in other kind of blocks, for instance, admonitions.

Imho, it does seem to be on purpouse, @mojavelinux can you confirm?

**Comment by vicmosin** [comment]
Here is the scenario: I want to add software's build/release number into documentation generated with asciidoc maven plugin and I want to see it as a part of real code snippet.
For example, to show how install actual software version with maven

**Comment by LightGuard** [comment]
Have you tried setting the subs attribute on the block (
http://asciidoctor.org/docs/user-manual/#applying-substitutions)?

On Tue, Sep 22, 2015 at 8:38 AM, Victor Mosin <notifications@github.com>
wrote:

> Here is the scenario: I want to add software's build/release number into
> documentation generated with asciidoc maven plugin and I want to see it as
> a part of real code snippet.
> For example, to show how install actual software version with maven
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asciidoctor/asciidoctor-maven-examples/issues/33#issuecomment-142307636>
> .
>



-- 
Jason Porter
http://en.gravatar.com/lightguardjp

**Comment by abelsromero** [comment]
> Have you tried setting the subs attribute on the block (
> http://asciidoctor.org/docs/user-manual/#applying-substitutions)?

Great obversavion, this worked just perfectly:

```
[source,xml,subs="attributes"]
----
Version: {project-version}
----
```

**Comment by vicmosin** [comment]
Perfect, thanks for fast response!

**Comment by mojavelinux** [comment]
Actually, you need to make sure to put `+` either before or after the word "attributes". Otherwise, you lose the other subs that you need for source blocks.

```
[source,xml,subs=attributes+]
----
Version: {project-version}
----
```

See http://asciidoctor.org/docs/user-manual/#applying-substitutions
