### ISSUE TITLE
Add an example that consume a ruby gem as extension

### ISSUE THREAD

**Issue by jmini** [asciidoctor/asciidoctor-maven-examples#41]
This was first mentioned in #27. It is great to have as example a maven project that consumes a ruby gem as extension (using the TorqueBox RubyGems Maven Proxy Repository):

> we will need another sub-project to show how to integrate ruby extensions

For the moment, `asciidoctor-pdf-with-theme-example` is using it, until #40 is fixed.

This issue keeps everything together:
- Mailing list: [asciidoctor-html5ruby broken?](http://discuss.asciidoctor.org/asciidoctor-html5ruby-broken-td4081.html)
- Example with `asciidoctor-pdf-cjk` in [asciidoctorj/#412](https://github.com/asciidoctor/asciidoctorj/issues/412#issuecomment-165040508)
- When the gem library declares version ranges as dependency (this is the case for `asciidoctor-bibtex`), maven downloads each version in each range. Some of those versions declare broken dependency which produces this maven error "Failed to collect rubygems dependencies!". This is documented in [jruby-maven-plugins/#57](https://github.com/torquebox/jruby-maven-plugins/issues/57). The solution is to declare each precise gem version in the `<gems>` section of the configuration.

**Comment by mojavelinux** [comment]
Thanks for pulling this together @jmini!

**Comment by abelsromero** [comment]
I was going to tackle this with with `asciidoctor-bibtex` and a silly question came to me. Should we add this as a ruby integration example or as bibtex example?
That means naming it something like `asciidoctor-rubygem-example` or as `asciidoctor-bibtex-example`?

**Comment by mojavelinux** [comment]
I'd just say name it after what it offers (bibtex integration), then we can reference it for what it does (ruby integration example).

**Comment by abelsromero** [comment]
I'm not sure `bibtex` can be integrated as it is. I get the following error:
```
Failed to collect dependencies at rubygems:citeproc-ruby:gem:1.1.0 -> rubygems:citeproc:gem:1.0.2 -> rubygems:namae:gem:0.8.2 -> rubygems:rubysl:gem:2.0.8 -> rubygems:rubysl-json:gem:[2.0,2.99999]: No versions available for rubygems:rubysl-json:gem:[2.0,2.99999] within specified range -> [Help 1]
```
And when I force the url in rubygems it says that the gem is no longer available https://rubygems.org/gems/rubysl-json.
Also, tried the exclude namae and add a newer version, but the error persists.
Before reporting why the exclusion/inclusion does not work to the gem-maven-plugin, I opened a request to bibtex to see if he cap upgrade the dependencies to newer versions.
https://github.com/ProgramFan/asciidoctor-bibtex/issues/4

**Comment by mojavelinux** [comment]
Sounds like getting those dependencies updated is the most practical path forward.

**Comment by jmini** [comment]
My understanding of the problem:
The problem with `bibtex` is that the ruby gem has defined version ranges as dependency.
When resolved with Maven, maven wants to download all versions in the range (and all their dependencies). Some of those versions are corrupt/broken/deleted [pick the correct one]. Maven is not able to compute the dependency graph as it normally does.
See: https://github.com/torquebox/jruby-maven-plugins/issues/57

There is a solution:
The `jruby-maven-plugins` allows fixing the entire gems versions (one fixed version per gem, no range). In that case the maven dependency graph calculation seems to be bypassed.
It works with: `<goal>sets</goal>` and `<gems>..</gems>` section in the configuration bock.

See the `gem-sets/pom.xml` example in this commit:
https://github.com/torquebox/jruby-maven-plugins/commit/f449bbae3790fa2477287ccce8131b151ea627d6 

@mojavelinux used this approach here:
https://github.com/asciidoctor/asciidoctorj/issues/412#issuecomment-165040508

I stopped working on this (for the moment) because I did not have the time to compute the ruby dependency graph (incl. the correct fixed version for each lib).

**Comment by abelsromero** [comment]
> The jruby-maven-plugins allows fixing the entire gems versions (one fixed version per gem, no range). In that case the maven dependency graph calculation seems to be bypassed.
> It works with: <goal>sets</goal> and <gems>..</gems> section in the configuration bock.

Thanks @jmini for the exaplanation. I will definitely give it a try to learn how to do this myself. But depending on the final required configuration I’m not sure if we should add an example like this.
On one side shows a complex case, I like that, but on the other it seems to me more of a gem-maven-plugin manual than an Asciidoctor. I’m not sure what to do.

**Comment by mkristian** [comment]
the only way to fix this problem with transitive dependencies where ALL artifacts got yanked is using exclusions and fix the dependency tree.
```
gem 'citeproc-ruby', '1.1.0', :exclusions => ['rubygems:namae']
gem 'namae', '~>0.8',' ~>0.8.3'
```
assuming here that citeproc-ruby is a declared dependency.

alternatively you can do something like this
```
gem 'citeproc-ruby', '1.1.0', :exclusions => ['rubygems:rubysl']
gem 'rubysl', '2.1.0'
```
hope this helps to "fix" the underlying dependency tree. with rubygems you just need to take care that the overwritten version is still within the declared ranges of the parent gem.

**Comment by mojavelinux** [comment]
If we could get the asciidoctor-mallard converter released, this would be an ideal use case since it has a minimum number of dependencies. The asciidoctor-bespoke plugin will be another good example. Neither is released yet, though.
