### ISSUE TITLE
can't specify the stylesheet to use with sourceHighlighter

### ISSUE THREAD

**Issue by jeremp** [asciidoctor/asciidoctor-maven-examples#49]
Hello ! 

I'm using the sourceHighlighter tag to hightlight my source code : 

`<sourceHighlighter>prettify</sourceHighlighter>`

... in the configuration tag.

When i use prettify for example it alway include an import to the default stylesheet : 

`<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/prettify/r298/prettify.min.css">`

Is there a way to set another stylesheet ?

**Comment by abelsromero** [comment]
For some code highlighters there are additional attributes precissely to set that.
See for instance 'prettifydir' and 'prettify-theme' in http://asciidoctor.org/docs/user-manual/#builtin-attributes.
You can set them in the `<attributes>` in the plugin configuration.
For instance you can have a local Prettify installation in your project and link it with 
```
    <attributes>
        <prettifydir>mydir</prettifydir>
    </attributes>
```
this will generate
```
<link rel="stylesheet" href="mydir/prettify.min.css">
<script src="mydir/prettify.min.js"></script>
```

Note you need to include the javascript also.

**Comment by jeremp** [comment]
I just tried with highlightjs and highlightjs-theme and it works !
Thank you !

**Comment by abelsromero** [comment]
Glad it was of help :)
I will close the issue then.
