### ISSUE TITLE
asciidoctor-diagram-example listed 2 times in readme

### ISSUE THREAD

**Issue by wimdeblauwe** [asciidoctor/asciidoctor-maven-examples#5]
This section is 2 times in the readme:

    link:asciidoctor-diagram-example/README.adoc[asciidoctor-diagram-example]::
    Demonstrates how to integrate Asciidoctor Diagram with the Asciidoctor Maven plugin.

**Comment by abelsromero** [comment]
OMG! it's true.
I can edit it, but if you'll like to fix it yourself :wink:, you can send a Pull Request that I'd be happy to merge.

**Comment by wimdeblauwe** [comment]
Go ahead, I am not near a computer soon :-)

Op zaterdag 10 januari 2015 heeft Abel Salgado Romero <
notifications@github.com> het volgende geschreven:

**Comment by abelsromero** [comment]
Done!
Thanks for reporting.

**Comment by mojavelinux** [comment]
Thanks for fixing!
