### ISSUE TITLE
Explain how to run a preprocessor before the build to revealjs

### ISSUE THREAD

**Issue by seinecle** [asciidoctor/asciidoctor-maven-examples#53]
Hi,
I am not a Maven expert...
My Java project uses the `asciidoctorj-pdf` maven lib to generate pdfs from adocs. Works fine, and I added a pre-processor. My class looks like:

        Asciidoctor asciidoctor = Asciidoctor.Factory.create();
        JavaExtensionRegistry extensionRegistry = asciidoctor.javaExtensionRegistry();
        extensionRegistry.preprocessor(ImagePreprocessor.class);

        Attributes attributes = new Attributes();
        Options options = new Options();

        options.setAttributes(attributes);
        options.setInPlace(true);
        options.setBackend("pdf");

        asciidoctor.convertFile(new File("sample.adoc"), options);

Now, using the plugins from asciidoctor-maven-examples I have created a revealJs presentation from the same sample.adoc. However the build process ignores the pre-processor I had written in my class.

To explain better what I mean, I expected to set "revealJs" instead of "pdf" as the backend in my code and then simply do `asciidoctor.convertFile(...)`

So how can I integrate the build to revealjs with the rest of my code?

**Comment by abelsromero** [comment]
I am not sure I understand the question, sorry. I see two things here.

If the question is '_How to add a pre-processor to the reveal.js maven build?_', there are a couple of options, the pure maven way is defining it in the [extensions option in the pom](https://github.com/asciidoctor/asciidoctor-maven-plugin#usage). 
If instead, you want a pure Java approach, you can use the [SPI](https://github.com/asciidoctor/asciidoctorj#extension-spi), here are the docs. Just create the proper file with the class name in the classpath and you are set.

Now, if the question is '_How do I replicate the reveal.js example using plain AsciidoctorJ (+ preprocessor extension) ?_'
Well, this is doable of course, but I am not sure this is the right approach.
The reveal.js integration requires 2 additional steps on top of the asciidoctor conversion invocation:
1. Download the reveal.js distribution: this contains the basic reveal.js css.
2. Integrate the reveal.js converter: this can be done as in the example or integrated as a gem using the `require` option.
Also, you will have to deal with some path configurations and minor details that the plugin takes care of.

**Comment by seinecle** [comment]
Hi,
Thanks! I have followed the SPI approach, neat! Yet the extension is loaded when I "run" the project in NetBeans (which triggers the maven plugin exec-maven-plugin that I added to the POM), but not when I trigger the other plugins (which are those from the POM of the revealjs example of this repo here).
As I am a noob in maven, I must miss something obvious?

**Comment by abelsromero** [comment]
I am really sorry, but I still don't get a clear idea of what you are trying to achieve.
If you can create a repo showing it, we can work on that.

**Comment by seinecle** [comment]
hi,
Thanks for your patience. I uploaded my project here:  


https://github.com/seinecle/asciidocjtest  


My intent:  
- overall: I am exploring how to use AsciiDocJ to write my courses and tutorials in adoc directly from NetBeans. The reason is that I will gain maximum flexibility in managing the toolchain for the conversion of these adocs to html, pdf, slides, and also explore other formats (pptx with Apache POI etc.)

- the constraint: I should preserve the simplicity of the conversion process and of keep the maintenance of the tool chain to a minimum. The goal is to write, not to spend a lot of devops time in the conversion process.

- Given my limited abilities (not a Maven champion, no time to invest in knowing it well), I'd prefer a flow where I'd setup the conversion processes directly from the Java code, not through Maven attributes etc.

- Ok, to the point now.
   - the conversion to pdf is simple: I execute the class ControllerMain, the pdf is generated
   - the conversion to slides is cumbersome:
      - first I run the pdf conversion, because it triggers the preprocessor which generates the adoc used for the slides conversion.
      - Then I run a custom goal in NetBeans which triggers the build of the slides. I have to check that parameters in the maven build are well set (path of the source folder, attributes for revealjs), which is inconvenient.
      - Then I need to find a way to copy the images used in the adoc from their original folder to the target folder where the slides have been generated.

   - My question: it would save me much time if I could control the generation of the slides directly from my ControllerMain class? Since so much of the generation logic seems to happen in the POM, I really don't know how I could do that.

Thanks for your help, and I remain available for more precisions!

**Comment by abelsromero** [comment]
Now I see!! 🎉 

And apologies if I sound rude, but I do think this is not the right approach. It's too complicated, adds some additional manteinance, and diverts from the aim of writting docs. don't you think?
Precisely our aim in Asciidoctor (and sub-projects) is to provide tools to focus on the documents mixing coder friendly practices, like the use of source repositories to manage versioning (e.g. GIT) or IDEs for writting. But end the end, it's about docs.

For the aim at hand, I'd use the maven plugin to manage the whole build instead of writting custom Java. The plugin can manage all your needs and you don't need to write any code. You insist you're not a Maven expert, but you already use a maven-exec task, so no excuses 😉 That's pretty pro imho.

My recomendation would be to go ahead with Maven, I'd create a branch with the whole setup, but I don't think it needs many changes. Basically it will replicate the way I work, in my current project we have a `docs` directory in some projects and a "only-doc" project we use instead of a wiki, we keep everything organized like images and other files and we render the output to html and pdf.
Also, if you don't mind, I'd recommend to check IntelliJ (community edition is free), it has a great AsciiDoc plugin with active manteinance right now. As soon as you

**Comment by abelsromero** [comment]
Last thing, with the maven approach, you can manage the different conversions with goals the same way you use the maven-exec, so shouldn't be a problem to use from NetBeans.

**Comment by abelsromero** [comment]
Progress report:
While doing the changes I realised the extensions needs to be in a sub-module. Basically, the project needs to be refactored like this https://github.com/asciidoctor/asciidoctor-maven-examples/tree/master/java-extension-example.
Not hard, but it adds another layer of complexity for non-Maven people. Still I think it's for the best.
I've been also exploring the pure Java approach and basically means creating you're own conversion tool. Which remind me that you may want to have a look at this https://github.com/asciidocfx/asciidocfx.

I have to start preparations for tonight now, so I don't think I can get it done today.

**Comment by seinecle** [comment]
Thanks. I have started using asciidocFx, which is great, but I found it not flexible enough still. This is why I follow a non GUI approach. I'll follow your advice and learn more about Maven to customize my projects as I need! For extensions, I'll have a look at the extension-example you mention.

**Comment by mojavelinux** [comment]
Where are we with this issue?

> I'd use the maven plugin to manage the whole build instead of writting custom Java.

I agree that once you move beyond just converting a single file with no extensions, you should probably be delegating to the build tool, such as Maven or Gradle. The plugins we have for those tools do all the things you are trying to do manually, such as load extensions, copy related files, and perform auxiliary tasks.

**Comment by seinecle** [comment]
Hi!

In terms of preference, I am still not at ease with putting lots of the editing-tool-chain-logic in Maven settings. I prefer coding things in Java and having Maven do the least possible. But that's a personal preference.

So in practice, I have stabilized my workflow, with java extensions which do a lot of the custom processing I need for each different output (slides / pdf / web).

**Comment by mojavelinux** [comment]
Excellent news!

Do you consider your original question resolved, then? If so, I'd like to close this issue so we can focus on the next challenge.
