### ISSUE TITLE
Question: How do you render the generated pdf on browser?

### ISSUE THREAD

**Issue by Tejansh** [asciidoctor/asciidoctor-maven-examples#54]
Hi,

**This is a question and not an issue**. I came across an application that I am expected to take over, at my work place. I am analyzing the code and came across the usage of asciidoc. This application is hosted in a machine that I cannot access and is running fine. I would want to understand how can I access the PDFs generated from asciidoc from my browser, and if I should be looking for the path being configured in the code/configuration somewhere?

The folder structure is:
--Master
    --doc
        --data
        --gradle 
        --src
              --docs
                     --images
                     --inc
                     --resources
                     --xyz.adoc
                     --abc.adoc
        --build.gradle
        --gradle.properties
        --pom.xml
            

Thanks,
Tejansh

**Comment by abelsromero** [comment]
Hi,
Apologies if I sound exaggerated , but I want to make sure I understand the question.
From your explanation, I get two possible interpretations.
1. "How can I make the generated PDF available from a web-browser?" That it, the app generates the PDFs and the end user must be able to open them though a link/button displayed on a web-app.
2. "How can I know the absolute path where the PDFs are generated to be able to retrieve them?"For instance, for validation. I that scenario you will be using some file browser, ftp, ssh shell.

I guess it's the first case, but can you confirm?

**Comment by Tejansh** [comment]
Hi,

Apologies the question looks really vague and not even close to what I was intending to ask in the first place. I actually wanted to know that how can the PDFs being generated be accessed? Are FTP, SSH or similar protocols the only choices? So, my pom.xml includes goals to generate the PDFs but there aren't an output directories mentioned. Thus, I was wondering if these PDFs are going to be rendered online or a default location?

**Comment by abelsromero** [comment]
To be honest, there's quite uncertainty here. I'll do my best, but if you don't know all details of the app, it's gonna be fun :dancer: .

Back to the topic...The app contains a pom.xml, gradle files and I guess Java code, any of them could be generating the PDFs.
If you have access to the code on you machine you can try to run the maven and gradle builds.
**Maven**: check the `<phase>` configured in the pom and invoke it to generate the docs. Default location is `${project.build.directory}/generated-docs`. The plugin's README page has the documentation (https://github.com/asciidoctor/asciidoctor-maven-plugin), see `outputdirectory`. Check if there's any profile set or the configuration is set in some parent.
**Gradle**: run the `asciidoctor` task, (from the shell do `gradlew asciidoctor` in Windows, `./gradlew asciidoctor` in *nix). Again, check the README for default values, the output is set in `oututDir`.

In both cases, the path is local to the root of the project. If that's the case, and somehow, the documents are generated with this process in the server (which is odd), you'll need to access using some remote propocol: ftp, ssh, RDP (Windows), etc. that will depends on your environment. You'll need to check with someone in your team.

**Java Code**: I think this is the more likely. you'll have to check the code and see what's going on. The complicated part is if the app uses some relative path. If you're lucky and is setting some absolute path it will be easier. In both cases look for calls to methods "toDir", "toFile", "setToDir" "setToFile" located in `Options` and `OptionsBuilder` classes (https://github.com/asciidoctor/asciidoctorj/blob/master/asciidoctorj-core/src/main/java/org/asciidoctor/Options.java, https://github.com/asciidoctor/asciidoctorj/blob/master/asciidoctorj-core/src/main/java/org/asciidoctor/OptionsBuilder.java).
If the app is web, maybe (big MAYBE) the files are generated in a statics resource path, so they're accessible using some URL. But again, you need some deep knowledge of the app to identify the paths and URL patterns setup.

**Comment by Tejansh** [comment]
Thanks a lot for your responses and support. Let me try and explore the app and the asciidoc usage and get back to you, on this thread. I shall close the issue and add comments later as and when I explore.
Thanks again!
