### ISSUE TITLE
An unordered list is not rendered correctly with a custom theme.

### ISSUE THREAD

**Issue by tobi-m** [asciidoctor/asciidoctor-maven-examples#57]
Hi,
in my [fork](/tobi-m/asciidoctor-maven-examples/tree/unordered-list) I added an unordered list. In the pdf output with a custom theme, the list is not rendered correctly. The character '¬' is shown, instead of the bullet points in the default theme example. An update of the dependencies did not help.

I ran the build in a cygwin bash shell and linux. On both systems the following line tries to give a hint:
"The following text could not be fully converted to the Windows-1252 character set:"

With the following older versions the problem does not occur:
<asciidoctorj.pdf.version>1.5.0-alpha.11</asciidoctorj.pdf.version>
<rubygems.prawn.version>2.1.0</rubygems.prawn.version>

Does someone know how to get it right?

**Comment by abelsromero** [comment]
This is not a problem with the versions or the maven plugin, it's a normal behaviour of asciidoctor-pdf themes.
It's all explained in detail here https://github.com/asciidoctor/asciidoctor-pdf/issues/409, but the summary is:

> if you have a custom theme, you have to specify everything. Otherwise, it defaults to using the PDF fonts (which are just useless)

The default fonts don't contain the special characters required, to set them, you can copy the `font.catalog` from the default theme https://github.com/asciidoctor/asciidoctor-pdf/blob/master/data/themes/default-theme.yml#L2 and then, set the `base.font_family` like here https://github.com/asciidoctor/asciidoctor-pdf/blob/master/data/themes/default-theme.yml#L41.
Note however, you may need to add the `font_family` attribute also to other sections for other special characters. For instance I had to add `literal.font_family` to make callouts work.

**Comment by mojavelinux** [comment]
Abel is correct. The '¬' (not) character is there to show you that the required glyph is missing from the font. This character only appears when using the AFM fonts, so it's an indication that you have not yet defined a custom TTF font to use. I've taken some steps in alpha.16 to avoid situations in which the not character appears, but in the end, it's only just a stop-gap until you define a custom TTF font.

More details can be found here: https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#fonts

**Comment by tobi-m** [comment]
Thank you very much for your quick and comprehensive answers. You guys are amazing!

With your help I could fix my problem with the following [commit](/tobi-m/asciidoctor-maven-examples/commit/ad849378f3a0f7f66e6659721d641c6a7ce53118).

The following steps were required:
* copy the fonts from the [default theme](/asciidoctor/asciidoctor-pdf/tree/master/data/fonts) to the project
* add the new folder with the fonts to the attributes section in the pom
`<pdf-fontsdir>${project.basedir}/src/fonts</pdf-fontsdir>`
* copy the `font.catalog` from the [default theme](/asciidoctor/asciidoctor-pdf/blob/master/data/themes/default-theme.yml#L2)
* set the `base.font_family` like [here](/asciidoctor/asciidoctor-pdf/blob/master/data/themes/default-theme.yml#L41) in the default theme

**Comment by abelsromero** [comment]
> copy the fonts from the default theme to the project

I don't think you need to copy them, they are already included in the gem/jar. Provided you keep the same font.catalog as-is, asciidoctor-pdf should be able to find them.

**Comment by mojavelinux** [comment]
Correct. If you use the built-in font names in your font catalog, you don't have to copy the fonts. Asciidoctor PDF will find them inside the gem package. If you use different fonts (or different filenames), then you have to copy them.

**Comment by tobi-m** [comment]
You are absolutely right. Works like a charm. Thank you so much for pointing it out.

Only these two steps, from Abel's first comment, are required when using the built-in font names:

* copy the `font.catalog` from the [default theme](/asciidoctor/asciidoctor-pdf/blob/master/data/themes/default-theme.yml#L2)
* set the `base.font_family` like [here](/asciidoctor/asciidoctor-pdf/blob/master/data/themes/default-theme.yml#L41) in the default theme

Moving forward to the newest version, helped a lot to tidy up a few spots in our manual with 878 pages.
