### ISSUE TITLE
error building asciidoctor-maven-examples

### ISSUE THREAD

**Issue by fredmoal** [asciidoctor/asciidoctor-maven-examples#65]
Trace
$ mvn
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Asciidoc to reveal.js Maven example 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- download-maven-plugin:1.2.1:wget (install-asciidoctor-revealjs) @ asciidoc-to-revealjs-example ---
Downloading: https://github.com/asciidoctor/asciidoctor-reveal.js/archive/master.zip
[INFO] /?
[INFO] --- download-maven-plugin:1.2.1:wget (install-revealjs) @ asciidoc-to-revealjs-example ---
Downloading: https://github.com/hakimel/reveal.js/archive/3.5.0.zip
[INFO] /?
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ asciidoc-to-revealjs-example ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Users\Fred\Downloads\asciidoctor-maven-examples-master\asciidoc-to-revealjs-example\src\main\resources
[INFO]
[INFO] --- asciidoctor-maven-plugin:1.5.6:process-asciidoc (generate-slides) @ asciidoc-to-revealjs-example ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
oct. 12, 2017 10:32:00 PM org.asciidoctor.internal.JRubyAsciidoctor renderFile
GRAVE: (RuntimeError) Could not find a converter to handle transform: document
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 46.392 s
[INFO] Finished at: 2017-10-12T22:32:00+02:00
[INFO] Final Memory: 31M/197M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.asciidoctor:asciidoctor-maven-plugin:1.5.6:process-asciidoc (generate-slides) on project asciidoc-to-revealjs-example: Execution generate-slides of goal org.asciidoctor:asciidoctor-maven-plugin:1.5.6:process-asciidoc failed: org.jruby.exceptions.RaiseException: (RuntimeError) Could not find a converter to handle transform: document -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

**Comment by abelsromero** [comment]
This was detected some days ago.
Long-story-short, the reveal.js pulls a gem directly from GitHub's `master` and a recent change broke the example.
* Solution 1: keep master and remove the `slim` part from the templates path
* Solution 2: use stable version of reveal.js (v1.0.4) converter gem instead of master.

I proposed option 2 in this PR [(#64),](https://github.com/asciidoctor/asciidoctor-maven-examples/pull/64) I am just waiting in case someone else wants to review it or has another possible solution.


If you are curious, full info is here: [#62](https://github.com/asciidoctor/asciidoctor-maven-examples/issues/62).

**Comment by mojavelinux** [comment]
I agree solution 2 is the way to go. The Reveal.js changed a lot recently to get organized into a new structure and to distribute it, but we can now expect that structure to remain stable from this point forward. So we should switch to official releases.

**Comment by abelsromero** [comment]
> I agree solution 2 is the way to go

I take that as a "PR accepted".

**Comment by fredmoal** [comment]
Sorry for the duplicate, and thank you for your explanations !
I agree with solution 2 too, "PR accepted"

**Comment by abelsromero** [comment]
I assume this can be closed.
