### ISSUE TITLE
Using yaml for pdf output?

### ISSUE THREAD

**Issue by seinecle** [asciidoctor/asciidoctor-maven-examples#66]
Just found that a human readable format exists to style the pdf output of Asciidoc:
https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc

Is there an example somewhere of how to use a yaml file with the Asciidoctor maven plugin? Thanks!

**Comment by abelsromero** [comment]
Thank @jmini for this: https://github.com/asciidoctor/asciidoctor-maven-examples/tree/master/asciidoctor-pdf-with-theme-example

**Comment by seinecle** [comment]
Oh great thanks! Pdf books here I come !!
