### ISSUE TITLE
Maven asciidoctor-confluence integration?

### ISSUE THREAD

**Issue by paul-nelson-baker** [asciidoctor/asciidoctor-maven-examples#74]
Is there support for asciidoctor-confluence? I would honestly love successful builds to automatically update our central documentation, but I can't figure out how to do this on my own

**Comment by abelsromero** [comment]
I am afraid not.
But it's not impossible, `asciidoctor-confluence` is a gem that runs asciidoctor cli and then uses  confluence REST API to push the generated HTML files.

It should be possible to write some code that does for you, some bash could to the trick. Just need to iterate over the generated files and do some curl calls. Or if you want to integrate it into a build:
* you can use the gmaven-plugin to embed some groovy
* switch to gradle and put the groovy/kotlin code in the build script itself
* use gulp-asciidoctor
....

There are more options like reusing the Ruby code, or use asciidoctor.js from a js bulding tool, but those seem more complicated to me.
