### ISSUE TITLE
source highlighting not working with revealjs

### ISSUE THREAD

**Issue by eiswind** [asciidoctor/asciidoctor-maven-examples#80]
this was working with the 1.5.8 versions, but i have no idea how to make it work with the revealjs backend. maybe this is a problem with asciidoctor at last?

**Comment by mojavelinux** [comment]
Is there more to this issue report? Just saying something "does not work" without any other information does not help us help you.

**Comment by eiswind** [comment]
If you run the revealjs example you will find that the source code is not highlighted. 

I made it work using the asciidoctor-revealjs gem and the rouge gem (don't know if I need that one ) that I installed with

```
<groupId>de.saumya.mojo</groupId>
<artifactId>gem-maven-plugin</artifactId>
```
then
```
<plugin>
                        <groupId>org.asciidoctor</groupId>
                        <artifactId>asciidoctor-maven-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>generate-slides</id>
                                <phase>process-resources</phase>
                                <goals>
                                    <goal>process-asciidoc</goal>
                                </goals>
                                <configuration>
                                    <requires>
                                        <require>asciidoctor-diagram</require>
                                        <require>asciidoctor-revealjs</require>
                                        <require>rouge</require>
                                    </requires>
                                    <sourceDocumentName>${source.document}.adoc</sourceDocumentName>
                                    <outputDirectory>${project.slides.directory}</outputDirectory>
                                    <outputFile>${project.slides.directory}/${source.document}.html</outputFile>
                                    <backend>revealjs</backend>
                                    <sourceHighlighter>rouge</sourceHighlighter>
                                    <attributes>
                                        <rouge-css>style</rouge-css>
                                        <rouge-style>${rouge.theme}</rouge-style>
                                        <revealjsdir>reveal.js-${revealjs.version}</revealjsdir>
                                        <revealjs_transition>linear</revealjs_transition>
                                        <project-version>${project.version}</project-version>
                                        <revealjs_customtheme>assets/solarized.css</revealjs_customtheme>
                                        <customcss>assets/custom.css</customcss>
                                    </attributes>
                                </configuration>
                            </execution>
```

does the trick.

**Comment by mojavelinux** [comment]
It's a lot simpler than that. For how the converter is being invoked, the backend value is incorrect. It should be:

```
revealjs:html
```

You should then be able to use either coderay or rouge as is this way. (You may need to supply some extra styles to make it look right, though).

When using templates, if you set the backend explicitly, you have to specify the basebackend too or else the processor will assume the filetype matches the name of the backend.

If the reveal.js converter were to be invoked as a gem, then this wouldn't be necessary since the converter sets the basebackend itself.

**Comment by mojavelinux** [comment]
I just submitted the fix.

**Comment by mojavelinux** [comment]
If you'd like to upgrade the example to use the asciidoctor-revealjs gem (similar to what you did to get rouge), that would be ideal. Then the backend only needs to be "revealjs" and the templates don't need to be specified.

**Comment by mojavelinux** [comment]
In other words, the asciidoctor-revealjs works just like a normal converter. The templates are an implementation detail and should not be exposed.

**Comment by eiswind** [comment]
Thanks for clearing that up!
If yould like to see the example using the asciidoctor-revealjs gem I could try and setup a pull request, just let me know.

Are there any benefits on doing it this way over using the first approach with revealjs:html?

**Comment by mojavelinux** [comment]
@eiswind Yes, that would be fantastic. Please proceed!

> Are there any benefits on doing it this way over using the first approach with revealjs:html?

Definitely. The templates are an implementation detail of that converter and using them directly bypasses some of the functionality in the converter. So the converter is just going to work better by calling it through the public API. You do that by loading it as a gem, setting the backend to 'revealjs', and allowing Asciidoctor to find it, instantiate it, and invoke it.

**Comment by mojavelinux** [comment]
Here's all the code that gets missed, btw: https://www.rubydoc.info/gems/asciidoctor-revealjs/2.0.0/Asciidoctor%2FRevealjs%2FConverter:initialize (click view source). But that code could expand. So anything not defined in the templates would be missed (and maybe one day the converter stops using the templates, or uses them in a different way).

**Comment by mojavelinux** [comment]
So while there are converters that use templates as the public API, the Asciidoctor Reveal.js is not one of those converters. (It just happens to be using them internally for easier maintenance).

**Comment by eiswind** [comment]
Good to know. 
I just opened pull request #81.
