### ISSUE TITLE
PDF header missing when migrating to asciidoctorj-pdf.1.5.0-alpha.18

### ISSUE THREAD

**Issue by PhilMFischer** [asciidoctor/asciidoctor-maven-examples#82]
I found some issue running the asciidoctor-pdf-with-theme-example with the latest version of ascidoctorj-pdf.1.5.0-alpha.18 as such:
```
<properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <asciidoctor.maven.plugin.version>2.0.0-RC.1</asciidoctor.maven.plugin.version>
        <asciidoctorj.pdf.version>1.5.0-alpha.18</asciidoctorj.pdf.version>
        <asciidoctorj.version>2.0.0</asciidoctorj.version>
        <jruby.version>9.2.7.0</jruby.version>
</properties>
```
Now the running content headers are dissapearing, the footers are still present as you can see in the attached image :confused: :

![asciidoctorj-pdf-missing-headers](https://user-images.githubusercontent.com/35496033/59927660-47cc5480-943d-11e9-967c-c1c516184351.png)

Contrary the alpha.17 does not seem to support the extends statement to the default theme
```
extends: default
```

**Comment by mojavelinux** [comment]
This is a known regression in alpha.18. You're going to need to wait for
beta.1.

Please consult resolved issues in asciidoctor-pdf to find out what's in the
pipeline.

>

**Comment by abelsromero** [comment]
I assume this is the related one: https://github.com/asciidoctor/asciidoctor-pdf/issues/1087

**Comment by tbayne** [comment]
@mojavelinux When is beta 1 due to drop?

**Comment by mojavelinux** [comment]
This week. I've just been wrapping up a few remaining issues to fix known bugs.

**Comment by slonopotamus** [comment]
This issue looks kinda outdated.

**Comment by mojavelinux** [comment]
Yes, this was a known issue that as long since been resolved.

**Comment by abelsromero** [comment]
Thanks for the update! :smile:
