### ISSUE TITLE
Question: Generated html maintaining folder structure

### ISSUE THREAD

**Issue by jambulud** [asciidoctor/asciidoctor-maven-examples#87]
Hello,

I'm trying to generate multiple html using asciidocs which are inside folders and subfolders but when the html files are generated, they end in generated-docs (without subfolders).
I have read the issue https://github.com/asciidoctor/asciidoctor/issues/1394 that solves this but using ruby asciidoctor and an "-R" flag. Is there a way to achieve the same with this asciidoctor-maven-plugin?

**Comment by abelsromero** [comment]
You can set `preserveDirectories` to true to achieve that (https://github.com/asciidoctor/asciidoctor-maven-plugin#configuration).
Also, have a look at `relativeBaseDir` in case your resources use relative paths to each other.

**Comment by jambulud** [comment]
It works perfectly, thanks!
