### ISSUE TITLE
[workaround] revealjs-example does not work with jruby 9.2.10.0 or higher

### ISSUE THREAD

**Issue by abelsromero** [asciidoctor/asciidoctor-maven-examples#98]
There's a related issue with gem-maven-plugin that prevents it from downloading the required gem during build, 9.2.10.0 version works fine.

Tracking upstream issue: https://github.com/torquebox/jruby-maven-plugins/issues/105

**Comment by abelsromero** [comment]
Applied fix to use older jruby version. But we are at mercy of jruby here.

**Comment by premanandc** [comment]
Didn't work with jruby version 9.2.9.0 or a lower version either (I tried 9.2.8.0). I get this the error below:
```
[ERROR] Failed to execute goal on project asciidoc-to-revealjs-example: Could not resolve dependencies for project org.asciidoctor.maven:asciidoc-to-revealjs-example:jar:1.0.0-SNAPSHOT: Failed to collect dependencies at rubygems:asciidoctor-revealjs:gem:3.0.0: Failed to read artifact descriptor for rubygems:asciidoctor-revealjs:gem:3.0.0: Could not transfer artifact rubygems:asciidoctor-revealjs:pom:3.0.0 from/to mavengems (mavengem:http://rubygems.org): (ArgumentError) marshal data too short -> [Help 1]
```

I had to replace the mavengems repository to use
```
        <repository>
            <id>mavengems</id>
            <url>mavengem:https://rubygems.org</url>
        </repository>
```
instead of **http**

**Comment by abelsromero** [comment]
Thanks for noticing and reporting!

> instead of **http**

It seems no longer support http, so we should definetly move to https. Care to make a PR?
